with open('src/pages/BuilderReportEditor.tsx', 'w') as f:
    f.write('''import React, { useState, useEffect } from 'react';
import { ArrowLeft, Save, Plus, Trash2, Database, Columns, Filter, Play, CheckCircle2, FileText, AlertCircle, RefreshCw, Type } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { cn } from '../lib/utils';

export default function BuilderReportEditor() {
  const navigate = useNavigate();
  const [reportTitle, setReportTitle] = useState('Untitled Report');
  const [reportDescription, setReportDescription] = useState('');
  const [reportHeader, setReportHeader] = useState('Confidential Report');
  const [reportFooter, setReportFooter] = useState('Generated by Builder System');
  
  const [selectedTable, setSelectedTable] = useState('users');
  const [availableColumns, setAvailableColumns] = useState<string[]>([]);
  const [selectedColumns, setSelectedColumns] = useState<string[]>([]);
  
  const [previewData, setPreviewData] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  
  const tables = [
    { id: 'users', name: 'Users' },
    { id: 'credentials', name: 'Credentials Report' },
    { id: 'classes', name: 'Classes' },
    { id: 'enrollments', name: 'Enrollments' },
    { id: 'programs', name: 'Programs' },
    { id: 'newsletters', name: 'Newsletters' },
    { id: 'announcements', name: 'Announcements' },
    { id: 'system_logs', name: 'System Logs' }
  ];

  useEffect(() => {
     let isMounted = true;
     const fetchSchema = async () => {
         const tableToQuery = selectedTable === 'credentials' ? 'users' : selectedTable;
         setLoading(true);
         try {
             const { data, error } = await supabase.from(tableToQuery).select('*').limit(1);
             if (isMounted) {
                 if (data && data.length > 0) {
                     const cols = Object.keys(data[0]);
                     setAvailableColumns(cols);
                     if (selectedTable === 'credentials') {
                         const credCols = cols.filter(c => ['user_id', 'user_name', 'email', 'password_hash', 'role'].includes(c));
                         setSelectedColumns(credCols.length > 0 ? credCols : cols.slice(0, 4));
                     } else {
                         setSelectedColumns(cols.slice(0, 4));
                     }
                 } else {
                     // Fallback for empty table
                     const fb = ['id', 'name', 'status', 'created_at'];
                     setAvailableColumns(fb);
                     setSelectedColumns(fb.slice(0, 2));
                 }
             }
         } catch (e: any) {
             console.error("Schema fetch error", e);
             if (isMounted) setError("Could not fetch table schema");
         } finally {
             if (isMounted) setLoading(false);
         }
     };
     
     fetchSchema();
     setPreviewData([]);
  }, [selectedTable]);

  const runPreview = async () => {
    if (selectedColumns.length === 0) {
        setError('Please select at least one column.');
        return;
    }
    setLoading(true);
    setError('');
    try {
        const tableToQuery = selectedTable === 'credentials' ? 'users' : selectedTable;
        // In case selected columns contains columns that do not exist (fallback case)
        const colsToSelect = selectedColumns.join(',');
        const { data, error: dbError } = await supabase
            .from(tableToQuery)
            .select(colsToSelect)
            .limit(15);
            
        if (dbError) throw dbError;
        setPreviewData(data || []);
    } catch (err: any) {
        console.error(err);
        setError(err.message || 'Failed to fetch data preview.');
    } finally {
        setLoading(false);
    }
  };

  const toggleColumn = (col: string) => {
      if (selectedColumns.includes(col)) {
          setSelectedColumns(selectedColumns.filter(c => c !== col));
      } else {
          setSelectedColumns([...selectedColumns, col]);
      }
  };

  const handleSave = () => {
      const reportConfig = {
          title: reportTitle,
          description: reportDescription,
          header: reportHeader,
          footer: reportFooter,
          table: selectedTable,
          columns: selectedColumns,
          updatedAt: new Date().toISOString()
      };
      
      const existing = JSON.parse(localStorage.getItem('custom_reports') || '[]');
      existing.push(reportConfig);
      localStorage.setItem('custom_reports', JSON.stringify(existing));
      
      alert('Report configuration saved successfully!');
      navigate('/builder/dashboard');
  };

  return (
    <div className="flex-1 flex flex-col h-full bg-surface overflow-hidden">
      {/* Header */}
      <header className="bg-surface-container-lowest border-b border-outline-variant/30 px-6 py-4 flex items-center justify-between shrink-0">
        <div className="flex items-center gap-4">
          <button 
            onClick={() => navigate('/builder/dashboard')}
            className="p-2 -ml-2 rounded-full hover:bg-surface-variant text-on-surface-variant transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <input 
               type="text" 
               value={reportTitle}
               onChange={(e) => setReportTitle(e.target.value)}
               className="font-display text-xl font-bold text-on-surface bg-transparent outline-none border-b border-transparent focus:border-primary transition-colors placeholder:text-outline"
               placeholder="Report Title"
            />
            <div className="flex items-center gap-2 mt-1">
               <FileText className="w-3.5 h-3.5 text-on-surface-variant" />
               <input 
                  type="text"
                  value={reportDescription}
                  onChange={(e) => setReportDescription(e.target.value)}
                  className="font-body text-xs text-on-surface-variant bg-transparent outline-none w-64 placeholder:text-outline"
                  placeholder="Add a description..."
               />
            </div>
          </div>
        </div>
        
        <div className="flex items-center gap-3">
           <button 
              onClick={runPreview}
              className="flex items-center gap-2 px-4 py-2 rounded-full bg-surface-variant text-on-surface-variant font-label font-bold text-sm hover:bg-surface-variant/80 transition-colors"
           >
              <Play className="w-4 h-4" />
              Run Preview
           </button>
           <button 
              onClick={handleSave}
              className="flex items-center gap-2 px-4 py-2 rounded-full bg-primary text-on-primary font-label font-bold text-sm hover:bg-primary/90 transition-colors shadow-sm"
           >
              <Save className="w-4 h-4" />
              Save Report
           </button>
        </div>
      </header>

      {/* Main Content Area */}
      <div className="flex-1 flex overflow-hidden">
         {/* Left Sidebar - Configuration */}
         <div className="w-80 bg-surface-container-lowest border-r border-outline-variant/30 flex flex-col shrink-0 overflow-y-auto">
            
            {/* Data Source */}
            <div className="p-6 border-b border-outline-variant/30">
               <h3 className="font-label font-bold text-sm text-on-surface uppercase tracking-wider mb-4 flex items-center gap-2">
                  <Database className="w-4 h-4 text-primary" />
                  Data Source
               </h3>
               
               <div className="space-y-2">
                  <label className="font-label text-xs font-bold text-on-surface-variant">Base Table</label>
                  <select 
                     value={selectedTable}
                     onChange={(e) => setSelectedTable(e.target.value)}
                     className="w-full px-3 py-2 rounded-xl border border-outline-variant/50 bg-surface text-on-surface font-body text-sm focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-all"
                  >
                     {tables.map(t => (
                         <option key={t.id} value={t.id}>{t.name}</option>
                     ))}
                  </select>
               </div>
            </div>
            
            {/* Layout Options (Header/Footer) */}
            <div className="p-6 border-b border-outline-variant/30">
               <h3 className="font-label font-bold text-sm text-on-surface uppercase tracking-wider mb-4 flex items-center gap-2">
                  <Type className="w-4 h-4 text-tertiary" />
                  Layout Options
               </h3>
               
               <div className="space-y-4">
                  <div className="space-y-1">
                      <label className="font-label text-xs font-bold text-on-surface-variant">Report Header</label>
                      <input 
                         type="text" 
                         value={reportHeader}
                         onChange={(e) => setReportHeader(e.target.value)}
                         className="w-full px-3 py-2 rounded-xl border border-outline-variant/50 bg-surface text-on-surface font-body text-sm focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-all"
                         placeholder="Header text"
                      />
                  </div>
                  <div className="space-y-1">
                      <label className="font-label text-xs font-bold text-on-surface-variant">Report Footer</label>
                      <input 
                         type="text" 
                         value={reportFooter}
                         onChange={(e) => setReportFooter(e.target.value)}
                         className="w-full px-3 py-2 rounded-xl border border-outline-variant/50 bg-surface text-on-surface font-body text-sm focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-all"
                         placeholder="Footer text"
                      />
                  </div>
               </div>
            </div>

            {/* Columns */}
            <div className="p-6 flex-1 border-b border-outline-variant/30">
               <div className="flex justify-between items-center mb-4">
                   <h3 className="font-label font-bold text-sm text-on-surface uppercase tracking-wider flex items-center gap-2">
                      <Columns className="w-4 h-4 text-secondary" />
                      Columns
                   </h3>
                   <span className="text-xs font-label text-on-surface-variant bg-surface-variant px-2 py-0.5 rounded-full">
                       {selectedColumns.length} selected
                   </span>
               </div>
               
               <div className="space-y-1">
                   {availableColumns.map(col => {
                       const isSelected = selectedColumns.includes(col);
                       return (
                           <button 
                               key={col}
                               onClick={() => toggleColumn(col)}
                               className={cn(
                                   "w-full flex items-center gap-3 px-3 py-2 rounded-xl transition-all text-left group",
                                   isSelected ? "bg-primary-container/30" : "hover:bg-surface-variant/50"
                               )}
                           >
                               <div className={cn(
                                   "w-5 h-5 rounded flex items-center justify-center shrink-0 border transition-colors",
                                   isSelected ? "bg-primary border-primary text-on-primary" : "border-outline-variant group-hover:border-primary/50"
                               )}>
                                   {isSelected && <CheckCircle2 className="w-3.5 h-3.5" />}
                               </div>
                               <span className={cn(
                                   "font-body text-sm truncate flex-1",
                                   isSelected ? "text-on-surface font-medium" : "text-on-surface-variant"
                               )}>
                                   {col}
                               </span>
                           </button>
                       );
                   })}
               </div>
            </div>
            
         </div>
         
         {/* Right Area - Preview */}
         <div className="flex-1 bg-surface-container-lowest p-6 md:p-8 overflow-y-auto">
             <div className="max-w-5xl mx-auto h-full flex flex-col">
                 <div className="flex justify-between items-center mb-6 shrink-0">
                     <h2 className="font-display text-xl font-bold text-on-surface">Data Preview</h2>
                     {loading && (
                         <div className="flex items-center gap-2 text-primary font-label text-sm font-bold">
                             <RefreshCw className="w-4 h-4 animate-spin" />
                             Loading...
                         </div>
                     )}
                 </div>
                 
                 {error ? (
                     <div className="bg-error-container/30 border border-error-container text-error p-6 rounded-2xl flex items-center gap-3">
                         <AlertCircle className="w-5 h-5 shrink-0" />
                         <p className="font-body text-sm">{error}</p>
                     </div>
                 ) : previewData.length > 0 ? (
                     <div className="flex-1 bg-surface rounded-2xl border border-outline-variant/30 overflow-hidden shadow-sm flex flex-col">
                         {reportHeader && (
                             <div className="p-4 border-b border-outline-variant/30 bg-surface-container-low/30">
                                 <h3 className="font-display font-bold text-lg text-on-surface">{reportHeader}</h3>
                             </div>
                         )}
                         <div className="overflow-x-auto flex-1">
                             <table className="w-full text-left border-collapse min-w-max">
                                 <thead>
                                     <tr>
                                         {selectedColumns.map(col => (
                                             <th key={col} className="p-4 border-b border-outline-variant/30 font-label text-xs font-bold text-on-surface-variant uppercase tracking-wider bg-surface-container-low/50 whitespace-nowrap">
                                                 {col.replace(/_/g, ' ')}
                                             </th>
                                         ))}
                                     </tr>
                                 </thead>
                                 <tbody className="font-body text-sm">
                                     {previewData.map((row, idx) => (
                                         <tr key={idx} className="border-b border-outline-variant/10 hover:bg-surface-variant/30 transition-colors">
                                             {selectedColumns.map(col => (
                                                 <td key={col} className="p-4 text-on-surface truncate max-w-[200px]">
                                                     {row[col] !== null && row[col] !== undefined 
                                                         ? (typeof row[col] === 'object' ? JSON.stringify(row[col]) : String(row[col]))
                                                         : <span className="text-outline italic">null</span>}
                                                 </td>
                                             ))}
                                         </tr>
                                     ))}
                                 </tbody>
                             </table>
                         </div>
                         <div className="bg-surface-container-low/50 border-t border-outline-variant/30 p-3 flex justify-between items-center text-xs font-label font-bold text-on-surface-variant">
                             {reportFooter ? <span>{reportFooter}</span> : <span></span>}
                             <span>Showing {previewData.length} preview rows</span>
                         </div>
                     </div>
                 ) : (
                     <div className="flex-1 flex flex-col items-center justify-center border-2 border-dashed border-outline-variant/50 rounded-3xl text-center p-12">
                         <div className="w-16 h-16 bg-surface-variant rounded-full flex items-center justify-center mb-4 text-on-surface-variant">
                             <Play className="w-8 h-8 ml-1" />
                         </div>
                         <h3 className="font-display text-lg font-bold text-on-surface mb-2">Ready to Preview</h3>
                         <p className="font-body text-sm text-on-surface-variant max-w-sm mb-6">
                             Select your data source and columns on the left, then click "Run Preview" to see the results.
                         </p>
                         <button 
                            onClick={runPreview}
                            className="bg-primary-container text-primary hover:bg-primary-container/80 px-6 py-2 rounded-full font-label font-bold transition-colors"
                         >
                            Run Preview
                         </button>
                     </div>
                 )}
             </div>
         </div>
      </div>
    </div>
  );
}
''')
