-- Create assignments table
CREATE TABLE IF NOT EXISTS assignments (
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id UUID REFERENCES classes(class_id) ON DELETE CASCADE,
    teacher_id UUID REFERENCES users(user_id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    due_date TIMESTAMPTZ,
    type TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create assignment_students table
CREATE TABLE IF NOT EXISTS assignment_students (
    assignment_student_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT REFERENCES assignments(assignment_id) ON DELETE CASCADE,
    student_id UUID REFERENCES users(user_id) ON DELETE CASCADE,
    status TEXT DEFAULT 'pending',
    grade TEXT,
    feedback TEXT,
    UNIQUE(assignment_id, student_id)
);

-- Enable RLS and add policies for local auth simulation
ALTER TABLE lesson_plans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for lesson_plans" ON lesson_plans;
CREATE POLICY "Enable all for lesson_plans" ON lesson_plans FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for assignments" ON assignments;
CREATE POLICY "Enable all for assignments" ON assignments FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE assignment_students ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for assignment_students" ON assignment_students;
CREATE POLICY "Enable all for assignment_students" ON assignment_students FOR ALL USING (true) WITH CHECK (true);

-- Allow duplicate emails by removing unique constraint on email if it exists
-- ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_key;
